### ISSUE TITLE
Hibernate uses wrong schema during schema validation when using postgresql

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#11]
The version of hibernate that we’re on has a bug that causes it to pick the wrong schema sometimes when it generates queries when we’re using postgresql. I am seeing the issue manifest as a "Missing column" exception during schema validation when eureka-services starts up and hibernate is initialized. Hibernate reports:
...
Caused by: org.hibernate.HibernateException: Missing column: active in eurekabackend.users
        at org.hibernate.mapping.Table.validateColumns(Table.java:366)
        at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1305)
        at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:155)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:509)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1794)
        at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:96)
        at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:914)
        ... 25 more

Hibernate should be validating the eureka service schema, but instead it is validating the eureka backend schema, which happens also to have a users table but without the active column.

Possibly relevant hibernate bug reports:
https://hibernate.atlassian.net/browse/HHH-9607 (closed as duplicate)
https://hibernate.atlassian.net/browse/HHH-9910 (fixed in version 5.0.0.CR3)

At first I thought that we could address the issue through privileges on the database, but that appears not to be the case. In postgresql there's no way to prevent a user from seeing the structure of schemas to which they have no privileges. For example, the eureka services user can see the structure of the eureka backend schema even though the eureka services user has no privileges on the eureka backend schema. So, the solution needs to come from hibernate. Hopefully, upgrading hibernate to version 5 will address the issue.

**Comment by candyam5522** [comment]
Migrate to hibernate 5 resolve this issue. A commit has been pushed.
[Migrate to Hibernate 5 on vm for postgreSQL6, Oracle6 and 7.docx](https://github.com/eurekaclinical/eureka/files/90619/Migrate.to.Hibernate.5.on.vm.for.postgreSQL6.Oracle6.and.7.docx)

**Comment by candyam5522** [comment]
Migrate to Hibernate5 resolve this issue, a commit has been pushed
[Migrate to Hibernate 5 on vm for postgreSQL+Oracle Centos6, and Oracle only Centos7.docx](https://github.com/eurekaclinical/eureka/files/90624/Migrate.to.Hibernate.5.on.vm.for.postgreSQL.Oracle.Centos6.and.Oracle.only.Centos7.docx)
