### ISSUE TITLE
eureka-protempa-etl fails to start if there's an error in JobRepairer

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#127]
It should still start but log the error.

Example:
```
Sep 14, 2016 4:25:00 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class edu.emory.cci.aiw.cvrg.eureka.etl.config.BackEndContextListener
java.lang.IllegalArgumentException: Unknown ordinal value [8] for enum class [org.eurekaclinical.eureka.client.comm.JobStatus]
        at org.hibernate.type.EnumType$OrdinalEnumValueMapper.fromOrdinal(EnumType.java:357)
        at org.hibernate.type.EnumType$OrdinalEnumValueMapper.getValue(EnumType.java:346)
        at org.hibernate.type.EnumType.nullSafeGet(EnumType.java:231)
        at org.hibernate.type.CustomType.nullSafeGet(CustomType.java:110)
        at org.hibernate.type.AbstractType.hydrate(AbstractType.java:85)
        at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2727)
        at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.loadFromResultSet(EntityReferenceInitializerImpl.java:308)
        at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateEntityState(EntityReferenceInitializerImpl.java:235)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:103)
        at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:112)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:122)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86)
        at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:88)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:682)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1991)
        at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:550)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:248)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:546)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:133)
        at org.hibernate.collection.internal.PersistentBag.toArray(PersistentBag.java:283)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at edu.emory.cci.aiw.cvrg.eureka.common.entity.JobEntity.getJobEventsInReverseOrder(JobEntity.java:305)
        at edu.emory.cci.aiw.cvrg.eureka.common.entity.JobEntity.getCurrentStatus(JobEntity.java:261)
        at edu.emory.cci.aiw.cvrg.eureka.etl.config.JobRepairer.repairIfNeeded(JobRepairer.java:75)
        at edu.emory.cci.aiw.cvrg.eureka.etl.config.EtlJobRepairerExecutor.doExecute(EtlJobRepairerExecutor.java:57)
        at edu.emory.cci.aiw.cvrg.eureka.etl.config.EntityManagerExecutor.execute(EntityManagerExecutor.java:62)
        at edu.emory.cci.aiw.cvrg.eureka.etl.config.BackEndContextListener.initDatabase(BackEndContextListener.java:100)
        at edu.emory.cci.aiw.cvrg.eureka.etl.config.BackEndContextListener.contextInitialized(BackEndContextListener.java:68)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by arpost** [comment]
This may be the behavior that we want. Could starting despite the error lead to data corruption?
