### ISSUE TITLE
ETL fails if the ontology doesn't contain a code that is in the spreadsheet

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#156]
```
SEVERE: Job 2 for user superuser failed: ETL failed for job 2
edu.emory.cci.aiw.cvrg.eureka.etl.job.EtlException: ETL failed for job 2
	at edu.emory.cci.aiw.cvrg.eureka.etl.job.ETL.run(ETL.java:160)
	at edu.emory.cci.aiw.cvrg.eureka.etl.job.Task.run(Task.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.protempa.QueryException: Query 1094e41d-1c7d-4812-a1e0-286eb392d599 failed
	at org.protempa.Executor$RetrieveDataThread.run(Executor.java:371)
Caused by: org.protempa.DataSourceReadException: Can't find left-hand-side of reference: keyId=11; references: org.protempa.UniqueIdPair@7092b6a1[referenceName=encounter,proposition=org.protempa.proposition.UniqueId@daf15d9[sourceId=org.protempa.proposition.DataSourceBackendId@6922cee6[id=Spreadsheet],localUniqueId=org.protempa.backend.dsb.relationaldb.SQLGenLocalUniqueId@41a8239a[entitySpecName=Diagnosis Codes,dbIds={B108},id=<null>,hashCode=1053610916,numericalId=382]],reference=org.protempa.proposition.UniqueId@10bd49ee[sourceId=org.protempa.proposition.DataSourceBackendId@6922cee6[id=Spreadsheet],localUniqueId=org.protempa.backend.dsb.relationaldb.SQLGenLocalUniqueId@654987fd[entitySpecName=Encounters,dbIds={45},id=<null>,hashCode=-1537344437,numericalId=45]]]
	at org.protempa.RefDataStreamerProcessor.fireKeyCompleted(RefDataStreamerProcessor.java:106)
	at org.protempa.DataStreamerProcessor.execute(DataStreamerProcessor.java:90)
	at org.protempa.DataStreamer.doStream(DataStreamer.java:69)
	at org.protempa.ReferenceLinkerPropositionDataStreamerProcessor.fireKeyCompleted(ReferenceLinkerPropositionDataStreamerProcessor.java:52)
	at org.protempa.DataStreamerProcessor.execute(DataStreamerProcessor.java:90)
	at org.protempa.MultiplexingDataStreamingEventIterator.hasNext(MultiplexingDataStreamingEventIterator.java:104)
	at org.protempa.DataStreamerIterator.advance(DataStreamerIterator.java:165)
	at org.protempa.DataStreamerIterator.hasNext(DataStreamerIterator.java:137)
	at org.protempa.MultiplexingDataStreamingEventIterator.hasNext(MultiplexingDataStreamingEventIterator.java:98)
	at org.protempa.Executor$RetrieveDataThread.run(Executor.java:364)
```

**Comment by arpost** [comment]
Fixed in eureka-3.0-Alpha-7 (which depends on protempa-4.0-Alpha-9).
