### ISSUE TITLE
Update jobs with deidentification turned on fail

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#38]
Here is the stack trace:
edu.emory.cci.aiw.cvrg.eureka.etl.job.EtlException: ETL failed for job ---
	at edu.emory.cci.aiw.cvrg.eureka.etl.job.ETL.run(ETL.java:144)
	at edu.emory.cci.aiw.cvrg.eureka.etl.job.Task.run(Task.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: DestinationOffset is not mapped [DELETE FROM DestinationOffset do WHERE do.destination = :d]
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1679)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1608)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:294)
	at edu.emory.cci.aiw.cvrg.eureka.etl.dao.JpaDestinationOffsetDao.deleteAll(JpaDestinationOffsetDao.java:82)
	at edu.emory.cci.aiw.cvrg.eureka.etl.dest.ProtempaDestinationFactory.getInstance(ProtempaDestinationFactory.java:105)
	at edu.emory.cci.aiw.cvrg.eureka.etl.dest.ProtempaDestinationFactory.getInstance(ProtempaDestinationFactory.java:83)
	at edu.emory.cci.aiw.cvrg.eureka.etl.job.ETL.run(ETL.java:123)
	... 4 more
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: DestinationOffset is not mapped [DELETE FROM DestinationOffset do WHERE do.destination = :d]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.generateQueryException(QuerySyntaxException.java:79)
	at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:218)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:142)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:76)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:150)
	at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:302)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:240)
	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1894)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:291)
	... 8 more
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: DestinationOffset is not mapped
	at org.hibernate.hql.internal.ast.util.SessionFactoryHelper.requireClassPersister(SessionFactoryHelper.java:171)
	at org.hibernate.hql.internal.ast.tree.FromElementFactory.addFromElement(FromElementFactory.java:91)
	at org.hibernate.hql.internal.ast.tree.FromClause.addFromElement(FromClause.java:76)
	at org.hibernate.hql.internal.ast.HqlSqlWalker.createFromElement(HqlSqlWalker.java:321)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElement(HqlSqlBaseWalker.java:3701)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElementList(HqlSqlBaseWalker.java:3590)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromClause(HqlSqlBaseWalker.java:716)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.deleteStatement(HqlSqlBaseWalker.java:445)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:273)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:262)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:190)
	... 16 more

**Comment by arpost** [comment]
This should be fixed, requires testing.

**Comment by candyam5522** [comment]
![img_9176](https://cloud.githubusercontent.com/assets/5263886/16019154/8eadcc2c-3175-11e6-8bf8-ce81c7a57b46.JPG)
![img_9177](https://cloud.githubusercontent.com/assets/5263886/16019156/8eb17b74-3175-11e6-9cda-1abe5a03137e.JPG)
![img_9178](https://cloud.githubusercontent.com/assets/5263886/16019155/8eb0f654-3175-11e6-88f7-62c1de06e577.JPG)

**Comment by candyam5522** [comment]
I set DEIDENTIFICATIONENABLED=true and ENCRYPTIONALGORITHM_ID =1, restart the tomcat, and run a job, looks like it finished okay, no error on stack trace
